matillion_dbt_test:
  outputs:
    dev:
      account: hermanmiller.us-east-1
      database: "{{ env_var('DBT_DATABASE') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('DBT_ROLE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
  target: dev